name: Deploy to Amazon ECS 'staging'

on:
  push:
    branches:
      - 'main'
  # pull_request:
  #   branches: [main, si-8]

env:
  AWS_REGION: "eu-west-1" 
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: yarn install
      run: yarn
    
    - name: Install ecs-deploy
      run: |
        curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
        sudo chmod +x /usr/bin/ecs-deploy

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_STAGING_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_STAGING_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
 
    - uses: MansaGroup/nrwl-nx-action@v2.0.6
      with:
        targets: deploy
        args: 
          --sha=${{ github.sha }}
          --ecr_registry=${{ steps.login-ecr.outputs.registry }}
          --env="staging"
