
name: Merge PR
on:
  push:
    branches:
      - 'main'
jobs:
  merge-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"