
name: Check
on:
  push:
    branches:
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: yarn install
        run: yarn
      - uses: MansaGroup/nrwl-nx-action@v2.0.6
        with:
          targets: lint,format:check,test,e2e,build,deploy
          affected: 'true'
