
name: Test
on:
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: yarn install
        run: yarn
      - name: check secrets
        env:
          SKEY: "key-${{ secrets.AWS_ACCESS_KEY_ID }}-key"
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo $SKEY
          echo $IMAGE_TAG
      # - name: deploy
      #   run: yarn affected:deploy
      # - name: check images
      #   run: docker image ls
      # - uses: MansaGroup/nrwl-nx-action@v2.0.6
      #   with:
      #     targets: lint,format:check,test,e2e
        

